export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAIL = "GET_ARTICLE_FAIL";

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const CREATE_NEW_ARTICLE_REQUEST = "CREATE_NEW_ARTICLE_REQUEST";
export const CREATE_NEW_ARTICLE_SUCCESS = "CREATE_NEW_ARTICLE_SUCCESS";
export const CREATE_NEW_ARTICLE_FAIL = "CREATE_NEW_ARTICLE_FAIL";

export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

export const ADD_FAVORITES_REQUEST = "ADD_FAVORITES_REQUEST";
export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITES_SUCCESS";
export const ADD_FAVORITES_FAIL = "ADD_FAVORITES_FAIL";

export const DELETE_FAVORITES_REQUEST = "DELETE_FAVORITES_REQUEST";
export const DELETE_FAVORITES_SUCCESS = "DELETE_FAVORITES_SUCCESS";
export const DELETE_FAVORITES_FAIL = "DELETE_FAVORITES_FAIL";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAIL = "EDIT_ARTICLE_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";