export const POST_NEW_USER_REQUEST = "POST_NEW_USER_REQUEST";
export const POST_NEW_USER_SUCCESS = "POST_NEW_USER_SUCCESS";
export const POST_NEW_USER_FAIL = "POST_NEW_USER_FAIL";

export const POST_LOGIN_USER_REQUEST = "POST_LOGIN_USER_REQUEST";
export const POST_LOGIN_USER_SUCCESS = "POST_LOGIN_USER_SUCCESS";
export const POST_LOGIN_USER_FAIL = "POST_LOGIN_USER_FAIL";

export const POST_HEADER_REQUEST = "POST_HEADER_REQUEST";
export const POST_HEADER_SUCCESS = "POST_HEADER_SUCCESS";
export const POST_HEADER_FAIL = "POST_HEADER_FAIL";